Rework structure
pixel-perfect-agency/next-foundation pull request #34
Opened 2023-06-09 14:42 UTC by Willem-Jaap

2023-06-20 14:36 UTC, frans-slabbekoorn requested changes

2023-06-20 15:05 UTC, frans-slabbekoorn approved these changes

2023-07-17 17:06 UTC, frans-slabbekoorn commented on docs/03-COMPONENTS.md
> +All NPM packages are also lowercase and hypen-case, to keep all imports consistent the project uses the same naming convention.
I prefer the hyphen casing

2023-07-17 20:07 UTC, Willem-Jaap commented on docs/03-COMPONENTS.md
> +All NPM packages are also lowercase and hypen-case, to keep all imports consistent the project uses the same naming convention.
hyphen casing it is.

2023-07-17 20:21 UTC, merged